name = "mikhbar-preview"
main = "src/index.js"
compatibility_date = "2026-09-23"
workers_dev = true

[assets]
directory = "../../dist/mikhbar"
binding = "ASSETS"
run_worker_first = true
html_handling = "auto-trailing-slash"
not_found_handling = "404-page"
