(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>{try{return new Intl.DateTimeFormat('ar-IQ',{year:'numeric',month:'long',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(d))}catch{return d||''}};
const categoryMap={ai:'الذكاء الاصطناعي',robotics:'الروبوتات',automation:'الأتمتة',mobile:'الهواتف',computers:'الحواسيب',apps:'التطبيقات',web:'الويب',social:'التواصل الاجتماعي',security:'الأمن التقني',announcements:'إعلانات المنصة'};
const slugFor=p=>p.categorySlug||'general';
let allPosts=[],visibleCount=12,currentFilter=document.body.dataset.category||'all';
function menu(){const b=$('.menu-button'),n=$('#navigation');if(!b||!n)return;b.addEventListener('click',()=>{const open=b.getAttribute('aria-expanded')!=='true';b.setAttribute('aria-expanded',String(open));n.classList.toggle('is-open',open)});$$('a',n).forEach(a=>a.addEventListener('click',()=>{b.setAttribute('aria-expanded','false');n.classList.remove('is-open')}));}
function card(p,i=0){const cat=esc(p.category||categoryMap[slugFor(p)]||'تقنية');const time=esc(p.dateLabel||fmt(p.date));const read=esc(p.readTime||'');return `<a class="rt-feed-item" href="${esc(p.url||'#')}"><div class="rt-feed-copy"><div class="rt-feed-kicker">${p.breaking?'<span class="rt-breaking">عاجل</span>':''}<span>${cat}</span></div><h3>${esc(p.title||'بدون عنوان')}</h3><p>${esc(p.excerpt||'')}</p><div class="rt-feed-time">${time}${read?` · ${read}`:''}</div></div><div class="rt-thumb" aria-hidden="true"></div></a>`}
function nowItem(p,i){return `<a class="rt-now-item" href="${esc(p.url||'#')}"><span class="rt-now-num">0${i+1}</span><span><strong>${esc(p.title||'')}</strong><small>${esc(p.dateLabel||fmt(p.date))}</small></span></a>`}
function filtered(){const q=($('#rtSearch')?.value||'').trim().toLowerCase();return allPosts.filter(p=>{const byCat=currentFilter==='all'||slugFor(p)===currentFilter;const hay=[p.title,p.excerpt,p.category,...(p.tags||[])].join(' ').toLowerCase();return byCat&&(!q||hay.includes(q))})}
function renderFeed(){const box=$('#rtFeed'),empty=$('#rtEmpty'),count=$('#rtCount'),more=$('#rtLoadMore');if(!box)return;const list=filtered();if(count)count.textContent=`${list.length} منشور`;box.innerHTML=list.slice(0,visibleCount).map(card).join('');if(empty)empty.hidden=!!list.length;if(more){more.style.display=list.length>visibleCount?'block':'none';more.onclick=()=>{visibleCount+=12;renderFeed()}}}
function renderHome(){if(!allPosts.length)return;const lead=$('#rtLead'),latest=$('#rtNowList');const featured=allPosts.find(p=>p.featured)||allPosts[0];if(lead&&featured){lead.href=featured.url||'#';$('#rtLeadCategory',lead).textContent=featured.category||categoryMap[slugFor(featured)]||'تقنية';$('#rtLeadTitle',lead).textContent=featured.title||'';$('#rtLeadExcerpt',lead).textContent=featured.excerpt||'';$('#rtLeadDate',lead).textContent=featured.dateLabel||fmt(featured.date);$('#rtLeadRead',lead).textContent=featured.readTime||''}if(latest){const list=allPosts.filter(p=>p!==featured).slice(0,5);latest.innerHTML=list.length?list.map(nowItem).join(''):'<div class="rt-empty-mini">ستظهر هنا الموضوعات الأحدث فور بدء النشر اليومي.</div>'}}
function renderCategory(){const slug=document.body.dataset.category;if(!slug)return;currentFilter=slug;const title=$('#rtCategoryCount');if(title)title.textContent=categoryMap[slug]||slug;renderFeed()}
async function load(){try{const r=await fetch('/forum/posts.json',{cache:'no-store'});if(!r.ok)throw 0;const data=await r.json();allPosts=(Array.isArray(data)?data:(data.posts||[])).slice().sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));renderHome();renderFeed();renderCategory()}catch{renderFeed()}}
function bind(){const search=$('#rtSearch');if(search)search.addEventListener('input',()=>{visibleCount=12;renderFeed()});$$('[data-filter]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();currentFilter=b.dataset.filter||'all';visibleCount=12;$$('[data-filter]').forEach(x=>x.removeAttribute('aria-current'));b.setAttribute('aria-current','page');renderFeed()}));}
function year(){$$('[data-year]').forEach(e=>e.textContent=new Date().getFullYear())}
menu();bind();year();load();
})();
