from __future__ import annotations

HUB_CONFIG = {
    "ai": {
        "ar": {
            "title": "أخبار الذكاء الاصطناعي وأدوات AI وتطبيقاته | مِخبار",
            "description": "تابع أخبار الذكاء الاصطناعي وأحدث برامج وأدوات AI وتطبيقاته، من ChatGPT وGemini وOpenAI إلى النماذج التوليدية والوكلاء الذكيين.",
            "summary": "أخبار الذكاء الاصطناعي وأدواته وبرامجه وتطبيقاته، مع متابعة النماذج والشركات والوكلاء الذكيين.",
            "heading": "أخبار وأدوات الذكاء الاصطناعي في مكان واحد",
            "body": "يجمع هذا القسم أخبار الذكاء الاصطناعي وتحديثات النماذج والأدوات والتطبيقات، بما يشمل OpenAI وChatGPT وGemini وClaude والنماذج مفتوحة الأوزان والوكلاء الذكيين والذكاء الاصطناعي التوليدي. نربط الأخبار بمصادرها ونحدّث التفاصيل عندما تتغير.",
            "links": (("apps", "التطبيقات والبرامج"), ("automation", "الأتمتة"), ("robotics", "الروبوتات"), ("security", "الأمن السيبراني")),
            "pillar": ("artificial-intelligence", "الدليل الشامل للذكاء الاصطناعي"),
        },
        "en": {
            "title": "Artificial Intelligence News Updates & AI Tools | Mikhbar",
            "description": "Follow artificial intelligence news updates on OpenAI, Google, Microsoft, open-source models, AI tools, agents and generative AI with source-linked reporting.",
            "summary": "Artificial intelligence news updates, AI tools, models, agents and applications with source-linked coverage.",
            "heading": "Artificial intelligence news, tools and model updates",
            "body": "This hub tracks artificial intelligence news across OpenAI, Google AI, Microsoft, Anthropic, open-source models, generative AI tools, coding agents and multimodal systems. Stories link back to their sources and are updated when material details change.",
            "links": (("apps", "apps and software"), ("automation", "automation"), ("robotics", "robotics"), ("security", "cybersecurity")),
            "pillar": ("artificial-intelligence", "the complete artificial intelligence guide"),
        },
    },
    "security": {
        "ar": {
            "title": "أخبار الأمن السيبراني والثغرات والحماية الرقمية | مِخبار",
            "description": "تابع أخبار الأمن السيبراني والثغرات والهجمات والبرمجيات الخبيثة والخصوصية وتحديثات الحماية الرقمية مع تغطية موثقة ومصادر واضحة.",
            "summary": "أخبار الأمن السيبراني والثغرات والخصوصية والهجمات وتحديثات الحماية الرقمية المهمة للمستخدمين والمؤسسات.",
            "heading": "الأمن السيبراني: ثغرات وهجمات وحماية رقمية",
            "body": "يركز هذا القسم على الثغرات الأمنية والهجمات النشطة والبرمجيات الخبيثة وتسريبات البيانات والخصوصية وتحديثات الحماية من Microsoft وGoogle وCISA وشركات الأمن. نوضح أثر الخبر ومن يتأثر وما إذا كان هناك تحديث أو تصحيح متاح.",
            "links": (("web", "أمن الويب"), ("apps", "التطبيقات والبرامج"), ("computers", "الحواسيب"), ("ai", "الذكاء الاصطناعي")),
            "pillar": ("cybersecurity", "دليل الأمن السيبراني والثغرات والحماية"),
        },
        "en": {
            "title": "Cybersecurity News, Vulnerabilities & Digital Security | Mikhbar",
            "description": "Follow cybersecurity news, active vulnerabilities, malware, privacy incidents, data breaches and digital security updates with source-linked reporting.",
            "summary": "Cybersecurity news covering vulnerabilities, malware, privacy, breaches and security updates that matter to users and organizations.",
            "heading": "Cybersecurity news, vulnerabilities and digital protection",
            "body": "This hub covers actively exploited vulnerabilities, malware, data breaches, privacy incidents and security updates from vendors and agencies including Microsoft, Google and CISA. Coverage explains who is affected, what changed and whether a patch or mitigation is available.",
            "links": (("web", "web security"), ("apps", "apps and software"), ("computers", "computing"), ("ai", "artificial intelligence")),
            "pillar": ("cybersecurity", "the cybersecurity, vulnerabilities and protection guide"),
        },
    },
    "automation": {
        "ar": {
            "title": "أخبار الأتمتة والوكلاء وسير العمل الذكي | مِخبار",
            "description": "أخبار الأتمتة وأدوات سير العمل والوكلاء الذكيين والسكربتات وRPA وGitHub Actions والأدوات التي تقلل العمل اليدوي وتربط الخدمات.",
            "summary": "أخبار أتمتة الأعمال وسير العمل والوكلاء والسكربتات والأدوات التي تربط الخدمات وتقلل العمل اليدوي.",
            "heading": "الأتمتة وسير العمل والوكلاء الذكيون",
            "body": "يجمع هذا القسم أخبار أتمتة الأعمال وسير العمل والوكلاء الذكيين والسكربتات وRPA وأدوات المطورين والتكامل بين الخدمات. نتابع الأدوات التي تحول المهام المتكررة إلى عمليات قابلة للتشغيل والمراقبة والتوسع.",
            "links": (("ai", "الذكاء الاصطناعي"), ("apps", "التطبيقات والبرامج"), ("web", "الويب"), ("robotics", "الروبوتات")),
        },
        "en": {
            "title": "Automation News, AI Agents & Workflow Tools | Mikhbar",
            "description": "Follow automation news, workflow tools, AI agents, scripts, RPA, GitHub Actions and integrations that connect services and reduce repetitive work.",
            "summary": "Automation news covering workflows, AI agents, scripts, integrations and tools that reduce repetitive digital work.",
            "heading": "Automation, workflow tools and AI agents",
            "body": "This hub follows workflow automation, AI agents, scripts, RPA, developer automation and service integrations. Coverage focuses on tools and systems that turn repetitive tasks into reliable processes that can be monitored, reused and scaled.",
            "links": (("ai", "artificial intelligence"), ("apps", "apps and software"), ("web", "web technology"), ("robotics", "robotics")),
        },
    },
    "robotics": {
        "ar": {
            "title": "أخبار الروبوتات والروبوتات البشرية والأنظمة الذكية | مِخبار",
            "description": "تابع أخبار الروبوتات البشرية والصناعية والروبوتات المتنقلة والحساسات والتحكم وPhysical AI والأتمتة في المصانع والأنظمة الذكية.",
            "summary": "أخبار الروبوتات البشرية والصناعية والأنظمة الذاتية والحساسات والتحكم والذكاء الاصطناعي المادي.",
            "heading": "الروبوتات البشرية والصناعية والذكاء الاصطناعي المادي",
            "body": "يغطي هذا القسم الروبوتات البشرية والصناعية والروبوتات المتنقلة والأنظمة الذاتية والحساسات والتحكم وPhysical AI والتصنيع الذكي. نتابع الشركات والمنصات والتجارب التي تنقل الذكاء الاصطناعي من البرمجيات إلى العالم المادي.",
            "links": (("ai", "الذكاء الاصطناعي"), ("automation", "الأتمتة"), ("computers", "الحواسيب"), ("security", "الأمن السيبراني")),
            "pillar": ("robotics", "دليل الروبوتات والروبوتات البشرية والذكاء الاصطناعي المادي"),
        },
        "en": {
            "title": "Robotics News, Humanoids & Intelligent Systems | Mikhbar",
            "description": "Follow robotics news on humanoids, industrial robots, autonomous systems, sensors, control, physical AI and intelligent manufacturing.",
            "summary": "Robotics news covering humanoids, industrial robots, autonomous systems, sensors, control and physical AI.",
            "heading": "Robotics, humanoids and physical AI",
            "body": "This hub tracks humanoid and industrial robots, autonomous machines, sensors, control systems, physical AI and intelligent manufacturing. Coverage follows the companies, platforms and experiments moving artificial intelligence into the physical world.",
            "links": (("ai", "artificial intelligence"), ("automation", "automation"), ("computers", "computing"), ("security", "cybersecurity")),
            "pillar": ("robotics", "the robotics, humanoids and physical AI guide"),
        },
    },
    "apps": {
        "ar": {
            "title": "أخبار التطبيقات والبرامج وأدوات الإنتاجية | مِخبار",
            "description": "تابع أخبار التطبيقات والبرامج وتحديثات الأدوات والخدمات الرقمية وبرامج سطح المكتب والهاتف وأدوات الإنتاجية الجديدة.",
            "summary": "أخبار التطبيقات والبرامج والخدمات الرقمية وتحديثات الأدوات وبرامج الإنتاجية على الهاتف وسطح المكتب.",
            "heading": "التطبيقات والبرامج والخدمات الرقمية",
            "body": "يركز هذا القسم على التطبيقات والبرامج والخدمات الرقمية وأدوات الإنتاجية، من تحديثات سطح المكتب والهاتف إلى المنصات والخدمات التي تغير طريقة العمل والاستخدام اليومي. نوضح المزايا الجديدة والتغييرات المهمة وتأثيرها العملي.",
            "links": (("mobile", "الهواتف"), ("ai", "الذكاء الاصطناعي"), ("web", "الويب"), ("security", "الأمن السيبراني")),
        },
        "en": {
            "title": "Apps & Software News, Updates & Productivity Tools | Mikhbar",
            "description": "Follow apps and software news, product updates, digital services, desktop and mobile software, productivity tools and important platform changes.",
            "summary": "Apps and software news covering product updates, digital services, desktop and mobile tools and productivity software.",
            "heading": "Apps, software and productivity tools",
            "body": "This hub covers apps, software, digital services and productivity tools, from desktop and mobile releases to platforms that change how people work and use technology. Coverage highlights meaningful features, updates and practical impact.",
            "links": (("mobile", "mobile"), ("ai", "artificial intelligence"), ("web", "web technology"), ("security", "cybersecurity")),
        },
    },
    "web": {
        "ar": {
            "title": "أخبار الويب والمتصفحات ومحركات البحث وتطوير الويب | مِخبار",
            "description": "أخبار الويب والمتصفحات ومحركات البحث والخدمات السحابية وتقنيات تطوير الويب وواجهات API وServerless والمنصات التي تشغل الإنترنت.",
            "summary": "أخبار الويب والمتصفحات ومحركات البحث والخدمات والمنصات وتقنيات تطوير الويب الحديثة.",
            "heading": "الويب والمتصفحات ومحركات البحث وتقنيات التطوير",
            "body": "يجمع هذا القسم أخبار الويب والمتصفحات ومحركات البحث والخدمات السحابية وواجهات API وServerless وأدوات تطوير المواقع والمنصات. نتابع التغييرات التي تؤثر في المطورين والمواقع وطريقة الوصول إلى المعلومات والخدمات على الإنترنت.",
            "links": (("security", "الأمن السيبراني"), ("apps", "التطبيقات والبرامج"), ("automation", "الأتمتة"), ("ai", "الذكاء الاصطناعي")),
        },
        "en": {
            "title": "Web Technology News, Browsers, Search & Development | Mikhbar",
            "description": "Follow web technology news across browsers, search engines, cloud services, APIs, serverless platforms and modern web development tools.",
            "summary": "Web technology news covering browsers, search engines, online services, APIs, cloud platforms and modern web development.",
            "heading": "Web technology, browsers, search and development",
            "body": "This hub follows browsers, search engines, cloud services, APIs, serverless platforms and modern web development tools. Coverage focuses on changes that affect developers, websites and how people discover and use services on the internet.",
            "links": (("security", "cybersecurity"), ("apps", "apps and software"), ("automation", "automation"), ("ai", "artificial intelligence")),
        },
    },
    "mobile": {
        "ar": {
            "title": "أخبار الهواتف وAndroid وiPhone والتقنيات المحمولة | مِخبار",
            "description": "تابع أخبار الهواتف وAndroid وiPhone وSamsung وPixel وتحديثات الأنظمة والأجهزة القابلة للطي والشرائح والتقنيات المحمولة الجديدة.",
            "summary": "أخبار الهواتف الذكية وAndroid وiPhone وتحديثات الأنظمة والأجهزة والشرائح والتقنيات المحمولة.",
            "heading": "الهواتف الذكية وAndroid وiPhone والتقنيات المحمولة",
            "body": "يغطي هذا القسم الهواتف الذكية وتحديثات Android وiOS وأجهزة iPhone وGalaxy وPixel والأجهزة القابلة للطي والشرائح والاتصال المحمول. نركز على التغييرات التي تؤثر فعلًا في الاستخدام اليومي، الأداء، الخصوصية، البطارية وتجربة التطبيقات.",
            "links": (("apps", "التطبيقات والبرامج"), ("security", "الأمن السيبراني"), ("computers", "الحواسيب"), ("ai", "الذكاء الاصطناعي")),
        },
        "en": {
            "title": "Mobile News, Android, iPhone & Smartphone Technology | Mikhbar",
            "description": "Follow mobile news across Android, iPhone, Samsung Galaxy, Google Pixel, OS updates, foldables, chips, connectivity and new smartphone technology.",
            "summary": "Mobile news covering Android, iPhone, operating-system updates, devices, chips, foldables and smartphone technology.",
            "heading": "Mobile technology, Android, iPhone and smartphones",
            "body": "This hub covers smartphones, Android and iOS updates, iPhone, Galaxy and Pixel devices, foldables, mobile chips and connectivity. Coverage focuses on changes that materially affect everyday use, performance, privacy, battery life and app experiences.",
            "links": (("apps", "apps and software"), ("security", "cybersecurity"), ("computers", "computing"), ("ai", "artificial intelligence")),
        },
    },
    "computers": {
        "ar": {
            "title": "أخبار الحواسيب وWindows وmacOS والعتاد والمعالجات | مِخبار",
            "description": "تابع أخبار الحواسيب وWindows وmacOS واللابتوبات والمعالجات وبطاقات الرسوميات والتخزين والعتاد وتحديثات الأنظمة المهمة.",
            "summary": "أخبار الحواسيب وWindows وmacOS واللابتوبات والمعالجات وبطاقات الرسوميات والتخزين والعتاد.",
            "heading": "الحواسيب والأنظمة والعتاد والمعالجات",
            "body": "يجمع هذا القسم أخبار الحواسيب المكتبية والمحمولة وWindows وmacOS والمعالجات وبطاقات الرسوميات والذاكرة والتخزين والشاشات والعتاد. نتابع الإطلاقات والتحديثات ومشكلات الأداء والأمان وما تعنيه عمليًا للمستخدمين والمطورين.",
            "links": (("mobile", "الهواتف"), ("apps", "التطبيقات والبرامج"), ("security", "الأمن السيبراني"), ("ai", "الذكاء الاصطناعي")),
        },
        "en": {
            "title": "Computer News, Windows, macOS, Hardware & Processors | Mikhbar",
            "description": "Follow computer news across Windows, macOS, laptops, CPUs, GPUs, storage, displays, hardware launches and important operating-system updates.",
            "summary": "Computer news covering Windows, macOS, laptops, processors, graphics, storage, displays and PC hardware.",
            "heading": "Computers, operating systems, hardware and processors",
            "body": "This hub covers desktop and laptop computers, Windows and macOS, processors, graphics cards, memory, storage, displays and PC hardware. Coverage tracks launches, system updates, performance issues and security changes that matter to users and developers.",
            "links": (("mobile", "mobile"), ("apps", "apps and software"), ("security", "cybersecurity"), ("ai", "artificial intelligence")),
        },
    },
    "social": {
        "ar": {
            "title": "أخبار منصات التواصل الاجتماعي وصناعة المحتوى | مِخبار",
            "description": "تابع أخبار فيسبوك وإنستغرام وتيك توك ويوتيوب وسناب شات وX، وتحديثات الخوارزميات وصناعة المحتوى وأدوات المبدعين والخصوصية.",
            "summary": "أخبار منصات التواصل الاجتماعي والخوارزميات وصناعة المحتوى وأدوات المبدعين والخصوصية والتحديثات الجديدة.",
            "heading": "منصات التواصل والخوارزميات وصناعة المحتوى",
            "body": "يغطي هذا القسم Facebook وInstagram وTikTok وYouTube وSnapchat وX وغيرها من المنصات، مع متابعة تغييرات الخوارزميات وأدوات المبدعين والإعلانات والخصوصية وسياسات النشر. نركز على ما يتغير فعليًا للمستخدمين وصناع المحتوى والمنشورات الرقمية.",
            "links": (("apps", "التطبيقات والبرامج"), ("web", "الويب"), ("security", "الأمن السيبراني"), ("ai", "الذكاء الاصطناعي")),
        },
        "en": {
            "title": "Social Media News, Platforms, Algorithms & Creators | Mikhbar",
            "description": "Follow social media news across Facebook, Instagram, TikTok, YouTube, Snapchat and X, including algorithms, creator tools, privacy and platform updates.",
            "summary": "Social media news covering platforms, algorithms, creator tools, privacy, publishing features and product updates.",
            "heading": "Social platforms, algorithms and the creator economy",
            "body": "This hub follows Facebook, Instagram, TikTok, YouTube, Snapchat, X and other social platforms, including algorithm changes, creator tools, advertising, privacy and publishing policies. Coverage focuses on changes that materially affect users, creators and digital publishers.",
            "links": (("apps", "apps and software"), ("web", "web technology"), ("security", "cybersecurity"), ("ai", "artificial intelligence")),
        },
    },
}

OLD_SUMMARIES = {
    "ai": {"ar": "أخبار النماذج والشركات والأدوات والمساعدات الذكية وتطبيقات الذكاء الاصطناعي.", "en": "News on AI models, companies, tools, assistants and real-world artificial intelligence applications."},
    "security": {"ar": "التحديثات الأمنية والخصوصية والحماية الرقمية والثغرات المهمة للمستخدمين.", "en": "Security updates, privacy, digital protection and vulnerabilities that matter to users."},
    "automation": {"ar": "أتمتة الأعمال وسير العمل والسكربتات والوكلاء والأدوات الذكية.", "en": "Workflow automation, scripts, agents and tools that automate digital work."},
    "robotics": {"ar": "الروبوتات البشرية والصناعية والحساسات والتحكم والمصانع الذكية.", "en": "Humanoid and industrial robots, sensors, control systems and intelligent manufacturing."},
    "apps": {"ar": "برامج سطح المكتب وتطبيقات الهاتف والخدمات الرقمية والأدوات الجديدة.", "en": "Desktop software, mobile apps, digital services and new productivity tools."},
    "web": {"ar": "المواقع والمتصفحات ومحركات البحث والخدمات وتقنيات تطوير الويب.", "en": "Websites, browsers, search engines, online services and modern web technologies."},
    "mobile": {"ar": "Android وiPhone والأجهزة الجديدة والتحديثات والمزايا والتقنيات المحمولة.", "en": "Android, iPhone, new devices, operating-system updates and mobile technology."},
    "computers": {"ar": "الحواسيب واللابتوبات والأنظمة والمعالجات وبطاقات الرسوميات والعتاد.", "en": "Computers, laptops, operating systems, processors, graphics and hardware."},
    "social": {"ar": "المنصات الاجتماعية والخوارزميات وصناعة المحتوى وأدوات المبدعين.", "en": "Social platforms, algorithms, creator tools and the creator economy."},
}
